# Generated by Django 5.0.4 on 2024-04-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
